### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by lrkwz** [gizur/docker-ftpserver#1]
Sorry I'm a docker newbie ;-) but I receive this error when building

    ~/docker-ftpserver> docker build --rm -t ftpserver .                                                                                                                     master
     Sending build context to Docker daemon 133.1 kB
    Sending build context to Docker daemon 
    Step 0 : FROM ubuntu:14.04
    ---> fa81ed084842
    Step 1 : MAINTAINER Jonas Colmsjö "jonas@gizur.com"
     ---> Running in a80bcfe3dff3
     ---> acb3e26506fb
    Removing intermediate container a80bcfe3dff3
    Step 2 : RUN apt-get update
     ---> Running in ee0771c42f1f
    Err http://archive.ubuntu.com trusty InRelease
      
    Err http://archive.ubuntu.com trusty-updates InRelease
      
    Err http://archive.ubuntu.com trusty-security InRelease
      
    Err http://archive.ubuntu.com trusty Release.gpg
       Could not resolve 'archive.ubuntu.com'
    Err http://archive.ubuntu.com trusty-updates Release.gpg
      Could not resolve 'archive.ubuntu.com'
    Err http://archive.ubuntu.com trusty-security Release.gpg
      Could not resolve 'archive.ubuntu.com'
    Reading package lists...
    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  
    
    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  
    
    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  
    
    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve     'archive.ubuntu.com'
   
    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not  resolve 'archive.ubuntu.com'
    
    W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'
   
     W: Some index files failed to download. They have been ignored, or old ones used instead.
    ---> 528eb8b3b75e
    Removing intermediate container ee0771c42f1f
    Step 3 : RUN apt-get install -y inetutils-ftp nano wget
     ---> Running in bd491d226351
      Reading package lists...
      Building dependency tree...
      Reading state information...
      E: Unable to locate package inetutils-ftp
      INFO[0002] The command "/bin/sh -c apt-get install -y inetutils-ftp nano wget" returned a non-zero   code: 100

**Comment by colmsjo** [comment]
This is not docker-related, it's a (very common) problem with your ubuntu mirror. Just try again or look up how to switch ubuntu mirror if the problem persists.
